Don't skip installation if upgrade flag is provided but version it's not
sous-chefs/pyenv pull request #78
Opened 2020-11-02 11:56 UTC by lukeseawalker

# Description

Don't skip installation if upgrade flag is provided (--upgrade) but version it's provided

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2020-11-02 11:56 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-02 20:35 UTC, ramereth commented
@lukeseawalker can you please address the two issues mentioned by kitchen-porter?

2020-11-03 08:46 UTC, lukeseawalker commented
@ramereth I'm not sure about the "Release Label Validator" check

2020-11-04 00:09 UTC, ramereth requested changes

2020-11-04 00:09 UTC, ramereth commented on resources/pip.rb
> +      end
Looking at this more closely, I feel a better approach might be to create a new `:upgrade` action which can properly deal with this logic a little better.

2020-11-04 18:26 UTC, ramereth commented
@lukeseawalker can you please update the documentation to reflect this new action?

2020-11-05 17:28 UTC, ramereth approved these changes

2020-11-05 17:43 UTC, merged